# Generated by Django 5.2.14 on 2026-05-26 01:08

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('artist', models.CharField(max_length=200, verbose_name='artista')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='género')),
                ('rating_user1', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='calificación usuario 1')),
                ('rating_user2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='calificación usuario 2')),
                ('spotify_url', models.URLField(blank=True, verbose_name='enlace Spotify')),
                ('tab_url', models.URLField(blank=True, verbose_name='enlace tablatura')),
                ('last_played_at', models.DateTimeField(blank=True, null=True, verbose_name='última vez en playlist')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'canción',
                'verbose_name_plural': 'canciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
