# Generated by Django 5.2.14 on 2026-05-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_playlist_playlistsong'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['artist', 'title'], 'verbose_name': 'canción', 'verbose_name_plural': 'canciones'},
        ),
        migrations.AddField(
            model_name='song',
            name='artwork_url',
            field=models.URLField(blank=True, verbose_name='portada'),
        ),
    ]
