# Generated by Django 5.2.14 on 2026-05-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_song_options_song_artwork_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='pública'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='share_token',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='token compartir'),
        ),
    ]
