# Generated by Django 5.2.14 on 2026-05-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0006_song_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, verbose_name='preview audio'),
        ),
    ]
