# Generated by Django 5.2.14 on 2026-05-29 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_alter_song_preview_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artwork_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='song',
            name='preview_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='preview audio'),
        ),
        migrations.AlterField(
            model_name='song',
            name='spotify_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='enlace Spotify'),
        ),
        migrations.AlterField(
            model_name='song',
            name='tab_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='enlace tablatura'),
        ),
    ]
